[package]
name = "smartcat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "*"
log = "*"
clap = { version = "*", features = ["derive"] }
ureq = { version="*", features = ["json"] }
serde = { version = "*", features = ["derive"] }
